export const movies = [
  {
    genres: [
      {
        id: 18,
        name: "Drama",
      },
      {
        id: 80,
        name: "Crimen",
      },
    ],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Don Vito Corleone, conocido dentro de los círculos del hampa como 'El Padrino', es el patriarca de una de las cinco familias que ejercen el mando de la Cosa Nostra en Nueva York en los años cuarenta. Don Corleone tiene cuatro hijos: una chica, Connie, y tres varones; Sonny, Michael y Fredo. Cuando el Padrino reclina intervenir en el negocio de estupefacientes, empieza una cruenta lucha de violentos episodios entre las distintas familias del crimen organizado.",
    poster_path: "/5HlLUsmsv60cZVTzVns9ICZD6zU.jpg",
    title: "El padrino",
    release_date: "1972-03-14",
    cast: [
      {
        adult: false,
        gender: 2,
        id: 3084,
        known_for_department: "Acting",
        name: "Marlon Brando",
        original_name: "Marlon Brando",
        popularity: 20.676,
        profile_path: "/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg",
        cast_id: 146,
        character: "Don Vito Corleone",
        credit_id: "6489aa85e2726001072483a9",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 1158,
        known_for_department: "Acting",
        name: "Al Pacino",
        original_name: "Al Pacino",
        popularity: 37.002,
        profile_path: "/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg",
        cast_id: 147,
        character: "Michael Corleone",
        credit_id: "6489aa936f8d9500afdf219c",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 3085,
        known_for_department: "Acting",
        name: "James Caan",
        original_name: "James Caan",
        popularity: 20.958,
        profile_path: "/v3flJtQEyczxENi29yJyvnN6LVt.jpg",
        cast_id: 148,
        character: "Sonny Corleone",
        credit_id: "6489aabc99259c00ff111136",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 3087,
        known_for_department: "Acting",
        name: "Robert Duvall",
        original_name: "Robert Duvall",
        popularity: 24.481,
        profile_path: "/ybMmK25h4IVtfE7qrnlVp47RQlh.jpg",
        cast_id: 149,
        character: "Tom Hagen",
        credit_id: "6489aace99259c011c42808d",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 3086,
        known_for_department: "Acting",
        name: "Richard S. Castellano",
        original_name: "Richard S. Castellano",
        popularity: 6.749,
        profile_path: "/1vr75BdHWret81vuSJ3ugiCBkxw.jpg",
        cast_id: 150,
        character: "Clemenza",
        credit_id: "6489aaf86f8d9500c88bea14",
        order: 4,
      },
      {
        adult: false,
        gender: 1,
        id: 3092,
        known_for_department: "Acting",
        name: "Diane Keaton",
        original_name: "Diane Keaton",
        popularity: 25.469,
        profile_path: "/siSWRRFN9uO6iCN7y9OrHU5IaJ.jpg",
        cast_id: 151,
        character: "Kay Adams",
        credit_id: "6489ab23bf31f25055a33a46",
        order: 5,
      },
      {
        adult: false,
        gender: 1,
        id: 3094,
        known_for_department: "Acting",
        name: "Talia Shire",
        original_name: "Talia Shire",
        popularity: 13.569,
        profile_path: "/oktJmlLeyYKBCWPNjHskDwAfjct.jpg",
        cast_id: 152,
        character: "Connie Corleone Rizzi",
        credit_id: "6489ab5799259c011c4280d8",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 3095,
        known_for_department: "Acting",
        name: "Gianni Russo",
        original_name: "Gianni Russo",
        popularity: 8.572,
        profile_path: "/jfeGnQfXMzKXsuSPm9oTxm6FOuz.jpg",
        cast_id: 153,
        character: "Carlo Rizzi",
        credit_id: "6489ab77e375c00139c26e5b",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 3088,
        known_for_department: "Acting",
        name: "Sterling Hayden",
        original_name: "Sterling Hayden",
        popularity: 9.477,
        profile_path: "/eRKaKeHjMKjNPOuENLccfVuyfVm.jpg",
        cast_id: 154,
        character: "Captain McCluskey",
        credit_id: "6489abe0d2b209014e0b8df9",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 3142,
        known_for_department: "Acting",
        name: "John Marley",
        original_name: "John Marley",
        popularity: 11.218,
        profile_path: "/xyzwd0CiBjXfowH3HcPhvuWcV5B.jpg",
        cast_id: 155,
        character: "Jack Woltz",
        credit_id: "6489ac0299259c011c42811f",
        order: 9,
      },
    ],
    director: {
      adult: false,
      gender: 2,
      id: 1776,
      known_for_department: "Directing",
      name: "Francis Ford Coppola",
      original_name: "Francis Ford Coppola",
      popularity: 27.479,
      profile_path: "/3Pblihd6KjXliie9vj4iQJwbNPU.jpg",
      credit_id: "5e92505cccb15f00136de455",
      department: "Directing",
      job: "Director",
    },
    seen: true,
    list_id: 1,
  },
  {
    genres: [
      {
        id: 28,
        name: "Acción",
      },
      {
        id: 18,
        name: "Drama",
      },
    ],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.",
    poster_path: "/zr4DkzWIMjaWtj6hlsbN6dnNeTX.jpg",
    title: "Los siete samuráis",
    release_date: "1954-04-26",
    cast: [
      {
        adult: false,
        gender: 2,
        id: 7450,
        known_for_department: "Acting",
        name: "三船敏郎",
        original_name: "三船敏郎",
        popularity: 13.586,
        profile_path: "/3A9PqrtiXHLp8B2JL7m3YvVXrmL.jpg",
        cast_id: 147,
        character: "Kikuchiyo",
        credit_id: "5e93b84654508d001517809e",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 7453,
        known_for_department: "Acting",
        name: "志村喬",
        original_name: "志村喬",
        popularity: 32.698,
        profile_path: "/ydyAm2vyBbEPZRICIMqqjDm0NM9.jpg",
        cast_id: 148,
        character: "Kambei Shimada",
        credit_id: "5e93b8737a97ab00140dea37",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 20828,
        known_for_department: "Acting",
        name: "Yoshio Inaba",
        original_name: "Yoshio Inaba",
        popularity: 3.417,
        profile_path: "/5qIAqM5PegWTNq67qNofz78fb6U.jpg",
        cast_id: 149,
        character: "Gorobei Katayama",
        credit_id: "5e93b8ae54508d00131770de",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 20829,
        known_for_department: "Acting",
        name: "Seiji Miyaguchi",
        original_name: "Seiji Miyaguchi",
        popularity: 4.204,
        profile_path: "/97XiJh1TSdu4hmJUp4Am5afgBZx.jpg",
        cast_id: 150,
        character: "Kyuzo",
        credit_id: "5e93b92c8e87020016ccf565",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 7454,
        known_for_department: "Acting",
        name: "Minoru Chiaki",
        original_name: "Minoru Chiaki",
        popularity: 8.124,
        profile_path: "/4uqny8n2OmGixVVdzqUBA5zJ9aW.jpg",
        cast_id: 151,
        character: "Heihachi Hayashida",
        credit_id: "5e93b96d54508d001517876a",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 7457,
        known_for_department: "Acting",
        name: "Daisuke Katō",
        original_name: "Daisuke Katō",
        popularity: 6.807,
        profile_path: "/7VATRGIU5NNhzdb6ZdJLKdqEvPW.jpg",
        cast_id: 152,
        character: "Shichiroji",
        credit_id: "5e93b9a72cde980014c4bcb9",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 20830,
        known_for_department: "Acting",
        name: "Isao Kimura",
        original_name: "Isao Kimura",
        popularity: 3.614,
        profile_path: "/afLPuf3x7UYXryAbqAGqmRcVNNW.jpg",
        cast_id: 153,
        character: "Katsushiro Okamoto",
        credit_id: "5e93b9d1ca4f6772c3806f40",
        order: 6,
      },
      {
        adult: false,
        gender: 1,
        id: 20831,
        known_for_department: "Acting",
        name: "津島恵子",
        original_name: "津島恵子",
        popularity: 5.897,
        profile_path: "/c4h0z00YkEUav0lGHoqVpeUzbul.jpg",
        cast_id: 154,
        character: "Shino",
        credit_id: "5e93ba18d55e4d00151a2e60",
        order: 7,
      },
      {
        adult: false,
        gender: 1,
        id: 554250,
        known_for_department: "Acting",
        name: "島崎雪子",
        original_name: "島崎雪子",
        popularity: 5.975,
        profile_path: "/wX1QqvkIdBQbNexTCxbmXyu6dUf.jpg",
        cast_id: 155,
        character: "Rikichi's Wife",
        credit_id: "5e93ba717a97ab00140deb89",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 96552,
        known_for_department: "Acting",
        name: "Kamatari Fujiwara",
        original_name: "Kamatari Fujiwara",
        popularity: 6.727,
        profile_path: "/tHosLdBr1JVudTdAm96prol6rah.jpg",
        cast_id: 156,
        character: "Manzô - Father of Shino",
        credit_id: "5e93ba9dca4f67001a814637",
        order: 9,
      },
    ],
    director: {
      adult: false,
      gender: 2,
      id: 5026,
      known_for_department: "Directing",
      name: "黒澤明",
      original_name: "黒澤明",
      popularity: 22.386,
      profile_path: "/eGexa6MZ22T1MZxce1qR3RcAYaS.jpg",
      credit_id: "52fe423bc3a36847f800dfdd",
      department: "Directing",
      job: "Director",
    },
    seen: false,
    list_id: 2,
  },
  {
    genres: [
      {
        id: 18,
        name: "Drama",
      },
      {
        id: 80,
        name: "Crimen",
      },
    ],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "Continuación de la saga de los Corleone con dos historias paralelas: la elección de Michael Corleone como jefe de los negocios familiares y los orígenes del patriarca, el ya fallecido Don Vito, primero en Sicilia y luego en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.",
    poster_path: "/mbry0W5PRylSUHsYzdiY2FSJwze.jpg",
    title: "El padrino. Parte II",
    release_date: "1974-12-20",
    cast: [
      {
        adult: false,
        gender: 2,
        id: 1158,
        known_for_department: "Acting",
        name: "Al Pacino",
        original_name: "Al Pacino",
        popularity: 37.002,
        profile_path: "/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg",
        cast_id: 8,
        character: "Don Michael Corleone",
        credit_id: "52fe422bc3a36847f8009505",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 3087,
        known_for_department: "Acting",
        name: "Robert Duvall",
        original_name: "Robert Duvall",
        popularity: 24.481,
        profile_path: "/ybMmK25h4IVtfE7qrnlVp47RQlh.jpg",
        cast_id: 9,
        character: "Tom Hagen",
        credit_id: "52fe422bc3a36847f8009509",
        order: 1,
      },
      {
        adult: false,
        gender: 1,
        id: 3092,
        known_for_department: "Acting",
        name: "Diane Keaton",
        original_name: "Diane Keaton",
        popularity: 25.469,
        profile_path: "/siSWRRFN9uO6iCN7y9OrHU5IaJ.jpg",
        cast_id: 10,
        character: "Kay Corleone",
        credit_id: "52fe422bc3a36847f800950d",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 380,
        known_for_department: "Acting",
        name: "Robert De Niro",
        original_name: "Robert De Niro",
        popularity: 51.98,
        profile_path: "/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg",
        cast_id: 11,
        character: "Vito Corleone",
        credit_id: "52fe422bc3a36847f8009511",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 3096,
        known_for_department: "Acting",
        name: "John Cazale",
        original_name: "John Cazale",
        popularity: 9.037,
        profile_path: "/41wXX1FBalyIuf5eaA4S43Y8IfZ.jpg",
        cast_id: 12,
        character: "Frederico 'Fredo' Corleone",
        credit_id: "52fe422bc3a36847f8009515",
        order: 4,
      },
      {
        adult: false,
        gender: 1,
        id: 3094,
        known_for_department: "Acting",
        name: "Talia Shire",
        original_name: "Talia Shire",
        popularity: 13.569,
        profile_path: "/oktJmlLeyYKBCWPNjHskDwAfjct.jpg",
        cast_id: 13,
        character: "Constanzia 'Connie' Corleone",
        credit_id: "52fe422bc3a36847f8009519",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 3171,
        known_for_department: "Acting",
        name: "Lee Strasberg",
        original_name: "Lee Strasberg",
        popularity: 6.548,
        profile_path: "/niSM7ejzddgaTcxjgJMYEFCr9Y2.jpg",
        cast_id: 14,
        character: "Hyman Roth",
        credit_id: "52fe422bc3a36847f800951d",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 3172,
        known_for_department: "Acting",
        name: "Michael V. Gazzo",
        original_name: "Michael V. Gazzo",
        popularity: 11.055,
        profile_path: "/cTY2Hlf6sIR9xLI95bBir7eI0N.jpg",
        cast_id: 15,
        character: "Frank Pentangeli",
        credit_id: "52fe422bc3a36847f8009521",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 3173,
        known_for_department: "Acting",
        name: "G. D. Spradlin",
        original_name: "G. D. Spradlin",
        popularity: 9.428,
        profile_path: "/pWNa9H3ABB3Ug9CwTfVNtHsCFjV.jpg",
        cast_id: 16,
        character: "Senator Pat Geary",
        credit_id: "52fe422bc3a36847f8009525",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 3174,
        known_for_department: "Acting",
        name: "Richard Bright",
        original_name: "Richard Bright",
        popularity: 11.307,
        profile_path: "/potMaJ2u5PRjXZb7qF9lSW1ldNZ.jpg",
        cast_id: 17,
        character: "Al Neri",
        credit_id: "52fe422bc3a36847f8009529",
        order: 9,
      },
    ],
    director: {
      adult: false,
      gender: 2,
      id: 1776,
      known_for_department: "Directing",
      name: "Francis Ford Coppola",
      original_name: "Francis Ford Coppola",
      popularity: 27.479,
      profile_path: "/3Pblihd6KjXliie9vj4iQJwbNPU.jpg",
      credit_id: "5e92517a8e87020016cb1d0e",
      department: "Directing",
      job: "Director",
    },
    seen: false,
    list_id: 3,
  },
  {
    genres: [
      {
        id: 53,
        name: "Suspense",
      },
      {
        id: 80,
        name: "Crimen",
      },
    ],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.",
    poster_path: "/hNcQAuquJxTxl2fJFs1R42DrWcf.jpg",
    title: "Pulp Fiction",
    release_date: "1994-09-10",
    cast: [
      {
        adult: false,
        gender: 2,
        id: 8891,
        known_for_department: "Acting",
        name: "John Travolta",
        original_name: "John Travolta",
        popularity: 45.497,
        profile_path: "/zkAX8YV692YVDQgRBh5JPUddPMQ.jpg",
        cast_id: 2,
        character: "Vincent Vega",
        credit_id: "52fe4269c3a36847f801ca99",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 2231,
        known_for_department: "Acting",
        name: "Samuel L. Jackson",
        original_name: "Samuel L. Jackson",
        popularity: 46.401,
        profile_path: "/nCJJ3NVksYNxIzEHcyC1XziwPVj.jpg",
        cast_id: 3,
        character: "Jules Winnfield",
        credit_id: "52fe4269c3a36847f801ca9d",
        order: 1,
      },
      {
        adult: false,
        gender: 1,
        id: 139,
        known_for_department: "Acting",
        name: "Uma Thurman",
        original_name: "Uma Thurman",
        popularity: 48.288,
        profile_path: "/xuxgPXyv6KjUHIM8cZaxx4ry25L.jpg",
        cast_id: 8,
        character: "Mia Wallace",
        credit_id: "52fe4269c3a36847f801cab7",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 62,
        known_for_department: "Acting",
        name: "Bruce Willis",
        original_name: "Bruce Willis",
        popularity: 43.485,
        profile_path: "/A1XBu3CffBpSK8HEIJM8q7Mn4lz.jpg",
        cast_id: 1,
        character: "Butch Coolidge",
        credit_id: "52fe4269c3a36847f801ca95",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 10182,
        known_for_department: "Acting",
        name: "Ving Rhames",
        original_name: "Ving Rhames",
        popularity: 30.294,
        profile_path: "/ohAOsD8E4tu35PI2buzZORpn9Ef.jpg",
        cast_id: 10,
        character: "Marsellus Wallace",
        credit_id: "52fe4269c3a36847f801cabf",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 1037,
        known_for_department: "Acting",
        name: "Harvey Keitel",
        original_name: "Harvey Keitel",
        popularity: 25.942,
        profile_path: "/7P30hza1neYWW3r7rSQOC736K2Z.jpg",
        cast_id: 7,
        character: "The Wolf",
        credit_id: "52fe4269c3a36847f801cab3",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 7036,
        known_for_department: "Acting",
        name: "Eric Stoltz",
        original_name: "Eric Stoltz",
        popularity: 18.337,
        profile_path: "/idFuM00MeVmwGAiqvDaJcBiLAmD.jpg",
        cast_id: 9,
        character: "Lance",
        credit_id: "52fe4269c3a36847f801cabb",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 3129,
        known_for_department: "Acting",
        name: "Tim Roth",
        original_name: "Tim Roth",
        popularity: 26.004,
        profile_path: "/qSizF2i9gz6c6DbAC5RoIq8sVqX.jpg",
        cast_id: 11,
        character: "Pumpkin",
        credit_id: "52fe4269c3a36847f801cac3",
        order: 7,
      },
      {
        adult: false,
        gender: 1,
        id: 99,
        known_for_department: "Acting",
        name: "Amanda Plummer",
        original_name: "Amanda Plummer",
        popularity: 25.766,
        profile_path: "/wEwyajjePFVVn2wFdH1NH7z9Qn5.jpg",
        cast_id: 12,
        character: "Honey Bunny",
        credit_id: "52fe4269c3a36847f801cac7",
        order: 8,
      },
      {
        adult: false,
        gender: 1,
        id: 2319,
        known_for_department: "Acting",
        name: "Maria de Medeiros",
        original_name: "Maria de Medeiros",
        popularity: 10.594,
        profile_path: "/xDo5mRSKXUZRmcZjUn42ICiyyI8.jpg",
        cast_id: 13,
        character: "Fabienne",
        credit_id: "52fe4269c3a36847f801cacb",
        order: 9,
      },
    ],
    director: {
      adult: false,
      gender: 2,
      id: 138,
      known_for_department: "Directing",
      name: "Quentin Tarantino",
      original_name: "Quentin Tarantino",
      popularity: 47.123,
      profile_path: "/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
      credit_id: "5e840df3da10f00018eb3962",
      department: "Directing",
      job: "Director",
    },
    seen: false,
    list_id: 4,
  },
  {
    genres: [
      {
        id: 18,
        name: "Drama",
      },
    ],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "Tras escuchar todos los testimonios y valorar las pruebas presentadas, un jurado popular compuesto por doce hombres tiene que decidir, por unanimidad, si absuelve o condena a muerte a un joven acusado de haber matado a su padre. Al principio, once están completamente convencidos de su culpabilidad y se inclinan por la condena, pero el que discrepa empieza a plantear dudas razonables que, poco a poco, van resquebrajando la inicial seguridad de los demás.",
    poster_path: "/t88XfoxO5cX3f0qaSxWsBS0Lc3.jpg",
    title: "12 hombres sin piedad",
    release_date: "1957-04-10",
    cast: [
      {
        adult: false,
        gender: 2,
        id: 1936,
        known_for_department: "Acting",
        name: "Martin Balsam",
        original_name: "Martin Balsam",
        popularity: 10.68,
        profile_path: "/iAc5RkmzMSGoLPFWUfqNayS41YE.jpg",
        cast_id: 57,
        character: "Juror 1",
        credit_id: "5e93b065cedac40016ebbd44",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 5247,
        known_for_department: "Acting",
        name: "John Fiedler",
        original_name: "John Fiedler",
        popularity: 13.628,
        profile_path: "/6vfLLGeGuO6Ko0VRnyhgE2v6RUu.jpg",
        cast_id: 58,
        character: "Juror 2",
        credit_id: "5e93b09a8e87020013cd34eb",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 5248,
        known_for_department: "Acting",
        name: "Lee J. Cobb",
        original_name: "Lee J. Cobb",
        popularity: 20.5,
        profile_path: "/aSQj0q6l734wxzutUGuYCGtJmZv.jpg",
        cast_id: 59,
        character: "Juror 3",
        credit_id: "5e93b0a584448e0014910883",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 5249,
        known_for_department: "Acting",
        name: "E.G. Marshall",
        original_name: "E.G. Marshall",
        popularity: 9.221,
        profile_path: "/psimeVoRk64DV7UNm4cLQylRFy2.jpg",
        cast_id: 60,
        character: "Juror 4",
        credit_id: "5e93b0ae7a97ab00120dd261",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 5250,
        known_for_department: "Acting",
        name: "Jack Klugman",
        original_name: "Jack Klugman",
        popularity: 9.033,
        profile_path: "/oJxveOxlunD8C9OczqKeryU0k6D.jpg",
        cast_id: 61,
        character: "Juror 5",
        credit_id: "5e93b0bd84448e001291147f",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 2651,
        known_for_department: "Acting",
        name: "Edward Binns",
        original_name: "Edward Binns",
        popularity: 9.838,
        profile_path: "/s3fk0d0fwuj6bDVP9AcPUXFsGmK.jpg",
        cast_id: 62,
        character: "Juror 6",
        credit_id: "5e93b0c8ccb15f00136fd2a4",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 5251,
        known_for_department: "Acting",
        name: "Jack Warden",
        original_name: "Jack Warden",
        popularity: 18.617,
        profile_path: "/hSShXiYMfRpMByaB5euZ59qCKN.jpg",
        cast_id: 63,
        character: "Juror 7",
        credit_id: "5e93b0d3875d1a001444ade1",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 4958,
        known_for_department: "Acting",
        name: "Henry Fonda",
        original_name: "Henry Fonda",
        popularity: 18.133,
        profile_path: "/6wXWsqSXF3wCsGcwVqiszy6RX9X.jpg",
        cast_id: 64,
        character: "Juror 8",
        credit_id: "5e93b0e254508d001a177bde",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 5252,
        known_for_department: "Acting",
        name: "Joseph Sweeney",
        original_name: "Joseph Sweeney",
        popularity: 7.929,
        profile_path: "/m0liVGH2JrhcvCr3buYUeXwhAyV.jpg",
        cast_id: 65,
        character: "Juror 9",
        credit_id: "5e93b0ec54508d0015176f37",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 39816,
        known_for_department: "Acting",
        name: "Ed Begley",
        original_name: "Ed Begley",
        popularity: 11.97,
        profile_path: "/AuPwjGgPphtfQOShb8pTtp5W7Ft.jpg",
        cast_id: 66,
        character: "Juror 10",
        credit_id: "5e93b0f7ca4f6700148145ab",
        order: 9,
      },
    ],
    director: {
      adult: false,
      gender: 2,
      id: 39996,
      known_for_department: "Directing",
      name: "Sidney Lumet",
      original_name: "Sidney Lumet",
      popularity: 10.488,
      profile_path: "/hjj3V2DkPJ46zo5uz9bsZQzAk6R.jpg",
      credit_id: "5e8e3c2f62e86f00159ba2f3",
      department: "Directing",
      job: "Director",
    },
    seen: false,
    list_id: 5,
  },
  {
    genres: [
      {
        id: 12,
        name: "Aventura",
      },
      {
        id: 36,
        name: "Historia",
      },
      {
        id: 10752,
        name: "Bélica",
      },
    ],
    id: 947,
    original_language: "en",
    original_title: "Lawrence of Arabia",
    overview:
      "Biografía de T.E. Lawrence. El Cairo, 1917. Un conflictivo y enigmático oficial británico es enviado al desierto árabe durante la Gran Guerra en la campaña de ayuda a Arabia contra Turquía. En el desierto, se hace amigo de Sherif Ali Ben El Kharish y pone todo su empeño en la ayuda a los árabes. Éstos creen que Lawrence es otro amante del desierto que ayuda porque cree que Arabia es débil, mientras que sus superiores británicos creen que se ha vuelto loco. Cuando los planes de Lawrence consiguen llevarse a cabo con éxito, comienza a ganarse enemigos.",
    poster_path: "/dC79NWawemFooYsKfNT0gAsVbER.jpg",
    title: "Lawrence de Arabia",
    release_date: "1962-12-11",
    cast: [
      {
        adult: false,
        gender: 2,
        id: 11390,
        known_for_department: "Acting",
        name: "Peter O'Toole",
        original_name: "Peter O'Toole",
        popularity: 19.797,
        profile_path: "/7HzyrEuRVPpjmyJTeiU5oILd3Cn.jpg",
        cast_id: 18,
        character: "T.E. Lawrence",
        credit_id: "52fe4291c3a36847f8028fa1",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 12248,
        known_for_department: "Acting",
        name: "Alec Guinness",
        original_name: "Alec Guinness",
        popularity: 12.972,
        profile_path: "/gplGgl6XERpvYdluiwY8GlxSdpi.jpg",
        cast_id: 19,
        character: "Prince Feisal",
        credit_id: "52fe4291c3a36847f8028fa5",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 5401,
        known_for_department: "Acting",
        name: "Anthony Quinn",
        original_name: "Anthony Quinn",
        popularity: 17.583,
        profile_path: "/hR3k16FaKgGoB7ENzfQHfwYKDDj.jpg",
        cast_id: 20,
        character: "Auda abu Tayi",
        credit_id: "52fe4291c3a36847f8028fa9",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 10018,
        known_for_department: "Acting",
        name: "Jack Hawkins",
        original_name: "Jack Hawkins",
        popularity: 11.495,
        profile_path: "/yxiqZ95wu8OhYyaPthv2UyXtHQO.jpg",
        cast_id: 21,
        character: "General Allenby",
        credit_id: "52fe4291c3a36847f8028fad",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 5004,
        known_for_department: "Acting",
        name: "Omar Sharif",
        original_name: "Omar Sharif",
        popularity: 12.106,
        profile_path: "/fY5azKFkoIGzyzMC51Y0Zrz58ju.jpg",
        cast_id: 22,
        character: "Sherif Ali",
        credit_id: "52fe4291c3a36847f8028fb1",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 12515,
        known_for_department: "Acting",
        name: "José Ferrer",
        original_name: "José Ferrer",
        popularity: 11.761,
        profile_path: "/mMOxqZz7Te7SHTd7AGqpjyyykb7.jpg",
        cast_id: 25,
        character: "Turkish Bey",
        credit_id: "52fe4291c3a36847f8028fbd",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 14371,
        known_for_department: "Acting",
        name: "Anthony Quayle",
        original_name: "Anthony Quayle",
        popularity: 7.709,
        profile_path: "/bAifisPoQh2zRkgaEZcUPe5TB9Q.jpg",
        cast_id: 24,
        character: "Colonel Harry Brighton",
        credit_id: "52fe4291c3a36847f8028fb9",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 4113,
        known_for_department: "Acting",
        name: "Claude Rains",
        original_name: "Claude Rains",
        popularity: 10.933,
        profile_path: "/fcM7Xfs0lWBw8TDjcFSLosX2YAD.jpg",
        cast_id: 23,
        character: "Mr. Dryden",
        credit_id: "52fe4291c3a36847f8028fb5",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 11128,
        known_for_department: "Acting",
        name: "Arthur Kennedy",
        original_name: "Arthur Kennedy",
        popularity: 11.095,
        profile_path: "/fDbTcQYSLDjfGetwF1mEwdFLSnG.jpg",
        cast_id: 26,
        character: "Jackson Bentley",
        credit_id: "52fe4291c3a36847f8028fc1",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 14372,
        known_for_department: "Acting",
        name: "Donald Wolfit",
        original_name: "Donald Wolfit",
        popularity: 2.733,
        profile_path: "/eRs3Bo7H3D2JwXbiurg9W40CgJb.jpg",
        cast_id: 27,
        character: "General Murray",
        credit_id: "52fe4291c3a36847f8028fc5",
        order: 9,
      },
    ],
    director: {
      adult: false,
      gender: 2,
      id: 12238,
      known_for_department: "Directing",
      name: "David Lean",
      original_name: "David Lean",
      popularity: 5.467,
      profile_path: "/dzwMuydy2x3JwaTBfBSq8c02qz4.jpg",
      credit_id: "52fe4291c3a36847f8028f43",
      department: "Directing",
      job: "Director",
    },
    seen: false,
    list_id: 6,
  },
];
